server:
  port: 8021
spring:
  #项目名称
  application:
    name: rabbitmq-provider
  #配置rabbitMq服务器
  rabbitmq:
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #消息确认配置项
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true